---
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
        
  - name: instalar filebeat
    yum:
      name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.7.0-x86_64.rpm
      state: present
      
  - name: ativar modulos "system"
    shell:
      cmd: filebeat modules enable system
    args:
      executable: /bin/bash
    when:
      - system_ext == true
      
  - name: copiar arquivos de configuração do logstash
    copy:
      src: "files/{{ item }}"
      dest: "/etc/filebeat/modules.d/{{ item }}"
    loop:
      - system.yml
    when:
      - system_ext == true
      
  - name: copiar arquivo de configuração do filebeat
    template:
      src: templates/filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
    notify:
      - start filebeat