---
  - name: upgrade all packages
    yum:
      name: '*'
      update_cache: yes
      state: latest
      security: yes
      
  - name: instalar python3 e pip3
    yum:
      name: "{{ package }}"
    vars:
      package:
        - python3
        - python3-pip
      
  - name: copiar ferramenta para host destino
    copy:
      src: files/warn.tar.gz
      dest: ~/warn.tar.gz
      
  - name: descompactar ferramenta
    unarchive:
      src: ~/warn.tar.gz
      dest: ~/
      remote_src: yes
      
  - name: instalar dependencias do
    shell:
      cmd: pip3 install -r ~/warn/requirements.txt
    args:
      executable: /bin/bash
