---
  - name: mongodb
    systemd:
      state: started
      name: mongod
      enabled: yes
      
  - name: elasticsearch
    systemd:
      state: started
      name: elasticsearch
      enabled: yes